### ISSUE TITLE
Node not found

### ISSUE THREAD

**Issue by 6ky** [HazemMeqdad/lavaplayer#27]
**Describe the bug**
Node not found

**To Reproduce**
https://github.com/HazemMeqdad/lavaplayer/blob/main/examples/dpy_base_v2/bot.py
this does not work it gives me that error i use windows 11.

**Expected behavior**
to run normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/80994667/171070385-489e91b9-7897-407e-a6c6-4b53669e45db.png)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser ?
 - Version ?

**Comment by HazemMeqdad** [comment]
Just check to `user_id` pram on LavalinkCLient
