### ISSUE TITLE
Lavaplayer won't play audio regardless of connected server

### ISSUE THREAD

**Issue by piotr25691** [HazemMeqdad/lavaplayer#29]
**Describe the bug**
No matter what Lavalink server I try to connect Lavaplayer to, it won't play any audio.

**To Reproduce**
1. Use lavaplayer 1.0.10a0
2. Tell the bot to play a song 
3. See the bot trying to play that song
4. Experience no audio being played back

**Expected behavior**
The bot should've played the audio or at least I should get an error pointing me to the issue.

**Screenshots**
I have no screenshots to explain this issue.

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 103

**Smartphone:**
 - Device: OnePlus Nord CE 5G
 - OS: Android 12
 - Browser: Chrome
 - Version: 104

**Additional context**
I have tried using two servers with this library, the preconfigured one at http://lava.link and the one I host myself on the VPS (3.5-rc3), none of them played audio. All I get is a message from the bot claiming it started playing the song, but nothing happened afterwards.

**Comment by HazemMeqdad** [comment]
hello my friend, are u got in the console message OnTrackStartEvent?

**Comment by piotr25691** [comment]
> hello my friend, are u got in the console message OnTrackStartEvent?

Nope, my bot should've logged it, however no event was emitted.

**Comment by HazemMeqdad** [comment]
are you examples?

**Comment by piotr25691** [comment]
> are you examples?

This is my own code I made. For some reason it refuses to play audio

**Comment by piotr25691** [comment]
> > > are you examples?
> > 
> > 
> > This is my own code I made. For some reason it refuses to play audio
> 
> The easiest way to help you would be to post your code directly.

Here's the code, you can check what's wrong.
https://pastebin.com/sCw6ejWK

**Comment by HazemMeqdad** [comment]
> > > > are you examples?
> > > 
> > > 
> > > This is my own code I made. For some reason it refuses to play audio
> > 
> > 
> > The easiest way to help you would be to post your code directly.
> 
> Here's the code, you can check what's wrong. https://pastebin.com/sCw6ejWK

can u show me `Lavalink` object?

**Comment by piotr25691** [comment]
> > > > > are you examples?
> > > > 
> > > > 
> > > > This is my own code I made. For some reason it refuses to play audio
> > > 
> > > 
> > > The easiest way to help you would be to post your code directly.
> > 
> > 
> > Here's the code, you can check what's wrong. https://pastebin.com/sCw6ejWK
> 
> can u show me `Lavalink` object?

```py
lava = Lavalink(host="62.171.160.186", port=2333, password="youshallnotpass", user_id=935862654138978314)
```

Port 2333 is open and the password is right, the bot ID also matches.

**Comment by piotr25691** [comment]
> > > > > > are you examples?
> > > > > 
> > > > > 
> > > > > This is my own code I made. For some reason it refuses to play audio
> > > > 
> > > > 
> > > > The easiest way to help you would be to post your code directly.
> > > 
> > > 
> > > Here's the code, you can check what's wrong. [pastebin.com/sCw6ejWK](https://pastebin.com/sCw6ejWK)
> > 
> > 
> > can u show me `Lavalink` object?
> 
> ```python
> lava = Lavalink(host="62.171.160.186", port=2333, password="youshallnotpass", user_id=935862654138978314)
> ```
> 
> Port 2333 is open and the password is right, the bot ID also matches.

I also noticed that my dev bot running on Windows connects just fine, just not the production one.

**Comment by piotr25691** [comment]
The issue was resolved on Lavalink's end but I cannot get my bot to play music from anywhere. I'm gonna blame this on my code and I'll be changing the libraries for music playback. Thank you for coming to my TED talk
