### ISSUE TITLE
[MISC] Add tinycord music bot example

### ISSUE THREAD

**Issue by xArty4** [HazemMeqdad/lavaplayer#3]
**Add tinycord music bot example**
If you can make a real quick example for tinycord. I would appreciate that.

**Comment by HazemMeqdad** [comment]
man this is only bug or issues not suggestions, you can create a example and create pull request

**Comment by xArty4** [comment]
Oh I forget that I can make pull requests sorry about that.

**Comment by HazemMeqdad** [comment]
dont worry

**Comment by HazemMeqdad** [comment]
This is suggested can you make for youself and create a pull request
