### ISSUE TITLE
'CacheMappingView' object has no attribute 'iterator'

### ISSUE THREAD

**Issue by mart337i** [HazemMeqdad/lavaplayer#34]
Hi 
I am having an issue with the join_command shown in the hikari / lightbulb example:

@bot.command()
@lightbulb.command(name="join", description="join voice channel")
@lightbulb.implements(*implements)
async def join_command(ctx: lightbulb.context.Context):
    states = bot.cache.get_voice_states_view_for_guild(ctx.guild_id)
    voice_state = [state async for state in states.iterator().filter(lambda i: i.user_id == ctx.author.id)]
    if not voice_state:
        await ctx.respond("you are not in a voice channel")
        return
    channel_id = voice_state[0].channel_id
    await bot.update_voice_state(ctx.guild_id, channel_id, self_deaf=True)
    await lavalink.wait_for_connection(ctx.guild_id)
    await ctx.respond(f"done join to <#{channel_id}>")
    
    I cant really seam to find a solution

**Comment by HazemMeqdad** [comment]
what is the problem? screenshot for it.

**Comment by HazemMeqdad** [comment]
In a new hikari version it update voice get to this
```py
voice_state = ctx.bot.cache.get_voice_state(ctx.guild_id, ctx.author.id)
```

**Comment by mart337i** [comment]
That fixed it. Thank you very much! and sorry for the late respons
