### ISSUE TITLE
Can't play any YouTube content, lavalink.auto_search_tracks return []

### ISSUE THREAD

**Issue by Tech-User42** [HazemMeqdad/lavaplayer#37]
Hello, without any change to the code, the lib suddently stopped letting me play YouTube video, because lavalink.auto_search_tracks return me an empty list, so i can't add any YouTube video to play.

Curiously any other mp3 stream link seams to work

**Comment by HazemMeqdad** [comment]
Hey this problem because your lavalink server version, just use latest version and this problem well be solve

**Comment by Tech-User42** [comment]
I feel so dumb, it works now thanks a lot !
