### ISSUE TITLE
bug skip

### ISSUE THREAD

**Issue by Rimuwu** [HazemMeqdad/lavaplayer#5]
Hello, there is such a bug, if you skip a track at once, and there are only 2 of them, then 2 tracks are skipped.

lavaplayer last version, 
nextcrod last version.

**Comment by HazemMeqdad** [comment]
you need to use `lavaplayer1.0.5a` this problem is fixed in lasted version

**Comment by HazemMeqdad** [comment]
Its work
![image](https://user-images.githubusercontent.com/66125469/152121355-ed79b43f-c9c3-46a4-91d2-b39264a89149.png)

**Comment by Rimuwu** [comment]
thanks
